In [2]:
import numpy as np

In [3]:
lista = [1, 2, 3]

In [4]:
lista

[1, 2, 3]

In [5]:
np.array(lista)

array([1, 2, 3])

In [6]:
matriz = [[1,2,3],[4,5,6],[7,8,9]]

In [7]:
matriz

[[1, 2, 3], [4, 5, 6], [7, 8, 9]]

In [8]:
np.array(matriz)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [10]:
np.arange(0, 10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [11]:
np.arange(0, 10, 2)

array([0, 2, 4, 6, 8])

In [12]:
np.zeros(3)

array([0., 0., 0.])

In [13]:
np.zeros((5,5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [14]:
np.ones((3,3))

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [15]:
np.eye(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [16]:
np.linspace(0, 10, 2)

array([ 0., 10.])

In [17]:
np.linspace(0, 10, 3)

array([ 0.,  5., 10.])

In [19]:
np.random.rand(5)

array([0.02212795, 0.25739209, 0.0456818 , 0.44757998, 0.54634642])

In [20]:
np.random.rand(5, 4)

array([[0.22889945, 0.98606556, 0.6971622 , 0.43861463],
       [0.11468308, 0.14277108, 0.94709798, 0.05617295],
       [0.04162682, 0.46755722, 0.8875786 , 0.47550077],
       [0.10475666, 0.54241135, 0.53907786, 0.53336511],
       [0.15978732, 0.69974537, 0.52177733, 0.09381527]])

In [21]:
np.random.randn(5, 4)

array([[ 0.58935412, -1.23213842,  2.24704558,  0.87990146],
       [-1.06591419,  0.02721117, -0.46737861,  0.67475906],
       [-0.88244536, -0.18378669, -1.76494324,  1.07411645],
       [-0.39001994, -0.2127581 , -1.8048259 , -0.86291281],
       [ 1.02877602, -1.11660116,  0.89546763, -0.27488026]])

In [22]:
np.random.rand(5)

array([0.20741681, 0.70770219, 0.50075245, 0.88969592, 0.21217149])

In [23]:
np.random.randn(5)

array([ 1.7353712 , -0.62102619, -0.87263445,  0.35351564, -0.00366268])

In [24]:
np.random.randint(0, 100, 10)

array([85, 99, 14,  1, 22, 31, 45, 35, 25, 15])

In [25]:
np.random.randint(0, 100, 100)

array([43,  2, 41, 44,  0, 85, 83, 18, 60, 35, 81, 98, 25, 27, 55, 72,  0,
       92, 99, 59, 42, 83, 99, 15, 24, 55, 29, 19, 85, 53,  4, 37, 27, 39,
       94, 18, 33, 83, 59, 86, 93, 87, 50, 15, 10, 63, 41, 25, 60, 63, 91,
       98, 39, 96, 57, 54, 57, 92, 10, 52, 17, 64, 32, 81, 22, 60, 97, 62,
        3, 45, 78, 97, 15, 81, 40, 12, 79, 73, 28, 57, 82, 79, 12, 47, 12,
       20, 93, 67, 91, 82, 77, 20, 94, 23,  1, 67, 15, 83, 45, 77])

In [26]:
np.round(np.random.rand(5) * 100)

array([42., 87., 62., 84., 47.])

In [27]:
np.round(np.random.rand(5) * 100, 0)

array([91.,  1., 13., 14., 96.])

In [28]:
np.random.rand(25)

array([0.36542782, 0.77590085, 0.10595365, 0.8913921 , 0.80001051,
       0.23574718, 0.41718952, 0.71074361, 0.68408556, 0.57077251,
       0.66192232, 0.34274197, 0.7054834 , 0.75365363, 0.14646077,
       0.10864391, 0.69223813, 0.00856864, 0.09338063, 0.35647089,
       0.13364666, 0.19187959, 0.61882561, 0.43192452, 0.7018438 ])

In [29]:
arr = np.random.rand(25)

In [30]:
arr.reshape((5, 5))

array([[0.56104828, 0.19727627, 0.97650179, 0.20761896, 0.69671991],
       [0.41764008, 0.85627995, 0.18953448, 0.74488523, 0.10777464],
       [0.7174172 , 0.98372117, 0.72359939, 0.39700266, 0.66024288],
       [0.34239216, 0.1730498 , 0.13921822, 0.61000251, 0.83630815],
       [0.48851457, 0.30293072, 0.60070611, 0.67995214, 0.92147278]])

In [31]:
arr

array([0.56104828, 0.19727627, 0.97650179, 0.20761896, 0.69671991,
       0.41764008, 0.85627995, 0.18953448, 0.74488523, 0.10777464,
       0.7174172 , 0.98372117, 0.72359939, 0.39700266, 0.66024288,
       0.34239216, 0.1730498 , 0.13921822, 0.61000251, 0.83630815,
       0.48851457, 0.30293072, 0.60070611, 0.67995214, 0.92147278])

In [32]:
arr = np.random.rand(25)

In [33]:
arr

array([0.75897371, 0.18892909, 0.77815493, 0.79088327, 0.99203074,
       0.02539211, 0.1527729 , 0.81562751, 0.76612519, 0.65136744,
       0.37387646, 0.33631417, 0.16507758, 0.51372495, 0.20883152,
       0.97580214, 0.41071673, 0.24033957, 0.90486553, 0.22896661,
       0.65260856, 0.68733263, 0.71523978, 0.8664202 , 0.56470108])

In [34]:
arr.max()

0.992030743372051

In [35]:
arr.min()

0.025392109902326987

In [36]:
arr.argmax()

4

In [37]:
arr.argmin()

5